name: gemini
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gemini: ^3.0.0
  dash_chat_2: 
    path: packages/dash_chat_2
  flutter_card_swiper: ^7.0.2
  pdf: ^3.11.3
  printing: ^5.14.2

  cupertino_icons: ^1.0.8
  video_player: ^2.9.5
  chewie: ^1.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - jsonfile/
    - videos/modulo1.mp4
    - videos/modulo2.mp4
    - videos/modulo3.mp4
    - assets/fonts/



  uses-material-design: true
